### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by unixorn** [joshjon/bliss-zsh#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license.

Please add a license - if you haven't already decided on one,  I recommend [choosealicense.com](https://choosealicense.com).

**Comment by joshjon** [comment]
License has been added 😁

**Comment by unixorn** [comment]
Thanks, adding in https://github.com/unixorn/awesome-zsh-plugins/pull/717
